{{ if .Values.global.config.createSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.name }}
  namespace: {{ .Values.global.namespace }}
type: Opaque
data:
  {{ .Values.secret.key }}: {{ .Values.global.secret_keys.brc | b64enc }}
{{end}}
