config:
  host: k8s-klanten-local.test,localhost,klanten-api.vng.cloud
  ingressHost: k8s-klanten-local.test

database:
  name: klanten

job:
  run: true

replicas:
  min: 1
  max: 2

cronjob:
  run: true
  # At 03:15 on day-of-month 1
  expression: "15 3 1 * *"

service:
  name: klanten
  port: 8000
  images:
    imageRepo: vngr/klanten-api
    tag: latest

secret:
  name: klanten-secret
  sentry: SENTRY_DSN
  key: SECRET_KEY
