config:
  host: k8s-klanten-local.test,localhost,klanten
cronjob:
  expression: 15 3 1 * *
database:
  name: klanten
replicas:
  max: 2
  min: 1
secret:
  key: SECRET_KEY
  name: klanten-secret
  sentry: SENTRY_DSN
service:
  images:
    imageRepo: vngr/klanten-api
    tag: 1.0.1
  name: klanten
  port: 8000
