apiVersion: apps/v1
kind: Deployment
metadata:
  name:  {{ .Values.service.name }}
  namespace: {{ .Values.global.namespace}}
  labels:
    {{- include "ri.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicas.min }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Values.service.name }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Values.service.name }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Values.service.name }}
          image: {{ .Values.service.images.imageRepo}}:{{ .Values.service.images.tag }}
          imagePullPolicy: {{ .Values.config.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
          env:
            - name: PORT
              value: :{{ .Values.service.port }}
          resources:
            requests:
              memory: "50Mi"
              cpu: "50m"
            limits:
              memory: "100Mi"
              cpu: "100m"
          readinessProbe:
            httpGet:
              path: /api/v1/health
              port: 8000
              httpHeaders:
                - name: Host
                  value: localhost
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /api/v1/health
              port: 8000
              httpHeaders:
                - name: Host
                  value: localhost
            initialDelaySeconds: 15
            periodSeconds: 30