{{ if .Values.global.config.createSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.global.secrets.name }}
  namespace: {{ .Values.global.namespace }}
type: Opaque
data:
  {{- range $key, $value := .Values.global.secretKeys }}
  secret-{{ $key }}: {{ $value | b64enc | nindent 4 }}
  {{- end }}
  {{- range $key, $value := .Values.global.secrets.data }}
  {{ $key }}: {{ $value | b64enc | nindent 4 }}
  {{- end }}
{{ end }}
