apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name:  {{ .Values.global.postgres.name }}-pvc
  namespace: {{ .Values.global.namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
