apiVersion: v1
kind: Service
metadata:
  name:  {{ .Values.global.postgres.name }}
  namespace: {{ .Values.global.namespace }}
spec:
  selector:
    {{- include "postgres.selectorLabels" . | nindent 8 }}
  ports:
    - name: "http"
      port: {{ .Values.global.postgres.service.port  }}
      targetPort: {{ .Values.global.postgres.service.port }}
