global:
  celery:
    name: celery
    secretName: celery
  config:
    certManager: false
    createCronJobs: false
    createJobs: true
    createSecret: true
    enableTLS: false
    environment: minikube
    kube: v1.26.1
    nginx: true
    pullPolicy: Always
  name: ri
  namespace: zgw
  postgres:
    name: postgres
    password: HbPL0pG6hW6eDmfvSPmKVqIv
    password_key: password
    secretName: postgres
    service:
      host: postgres
      port: 5432
    username: postgres
    username_key: username
  rabbitmq:
    default_password: 82WE7gS8S7QGj1Hg6VSex6Zo
    default_user: nrc_root
    name: rabbitmq
    port: 5672
    secretName: rabbitmq
  redis:
    database: 7
    host: redis-test
    name: redis
    service:
      port: 6379
  secret_keys:
    ac: ghuw!*n17r2_66k2&8ty0d)sile!gu78zaw8(x$b1%cmd$_e!s
    brc: jwj72bv1d!-a!s=8)c0cw%vzt^nkz-)ph8gi=d-+2x4^^w79$#
    drc: $ji8rxl#%$64@^u610=u@@$o3dm@d9v%9%2fv=629k^kk0l!@h
    nrc: g@@17dew+&zxn2w@tke_ni#xduh**!bl%hp(68t4f4nq9n^v+f
    zrc: busjadv=7pg5!d4oq6a0n%=^f9*s)vv0f_z@r9thm!5f_2!i11
    ztc: fd^gn1ska(y(u30n=-3ad8540_4!9x1pgtwn521u63!ll^v41n
  tokenIssuer:
    identifier: token-issuer-seeded
    identifierKey: identifierTokens
    secret: TvxAYQJJKugJpQvSdCm5JnMN
    secretKey: secretTokens
    secretName: token-seeder
  tokenSeeder:
    imagePullPolicy: Never
    imageRepo: ghcr.io/vng-realisatie/token-seeder
    pullPolicy: Always
    secret: mIcgoLS7ANbK6Mvxrv8qfo4Q
    secretKey: internalToken
    tag: 0.0.5
ingress:
  instance: zgw-stable
  name: ref-implementatie
  services:
  - host: k8s-zrc-local.test
    name: zrc
    port: 8000
  - host: k8s-drc-local.test
    name: drc
    port: 8000
  - host: k8s-ztc-local.test
    name: ztc
    port: 8000
  - host: k8s-ac-local.test
    name: ac
    port: 8000
  - host: k8s-brc-local.test
    name: brc
    port: 8000
  - host: k8s-nrc-local.test
    name: nrc
    port: 8000
  - host: k8s-klanten-local.test
    name: klanten
    port: 8000
  - host: k8s-contactmomenten-local.test
    name: contactmomenten
    port: 8000
  - host: k8s-verzoeken-local.test
    name: verzoeken
    port: 8000
  - host: k8s-vrl-local.test
    name: vrl
    port: 8000
  - host: k8s-tokens-local.test
    name: token-issuer
    port: 8000
postgres:
  images:
    imageRepo: mdillon/postgis
    tag: latest
redis:
  images:
    imageRepo: redis
    tag: 5-alpine
services:
  ac:
    enabled: true
  brc:
    enabled: true
  contactmomenten:
    enabled: true
  drc:
    enabled: true
  klanten:
    enabled: true
  nrc:
    enabled: true
  token-issuer:
    enabled: true
  verzoeken:
    enabled: true
  vrl:
    enabled: true
  zrc:
    enabled: true
  ztc:
    enabled: true
