global:
  celery:
    name: celery
    secretName: celery
  config:
    certManager: true
    createCronJobs: false
    createJobs: true
    createSecret: true
    enableTLS: false
    environment: minikube
    kube: v1.26.1
    nginx: false
    pullPolicy: Always
  name: ri
  namespace: zgw
  postgres:
    name: postgres
    password: hywKZ8i1RV1dC8iWRANSMREt
    password_key: password
    secretName: postgres
    service:
      host: postgres
      port: 5432
    username: postgres
    username_key: username
  rabbitmq:
    default_password: oAKvujJUJnx7Ktffizt5zf0E
    default_user: nrc_root
    name: rabbitmq
    port: 5672
    secretName: rabbitmq
  redis:
    database: 7
    host: redis-test
    name: redis
    service:
      port: 6379
  secret_keys:
    ac: n&f3^v=#n(yn_&jgea1qy&hiq8hc^=9@$$h^08^ut!a1ivlvpr
    brc: 7tt6m45#852%9&e9v*y!r#plbj%$9o@^moxf6%buse7xhh31d%
    drc: bxh2x4tn5mt@zdktoec%r@5dbmznf-uh2fbes-jim$p%$o8$8v
    nrc: spt5d&()yn6*wq$*ufsepmiob6wfp+5@%--e(og@j$-4mcqa1g
    zrc: r#i6#%xt#5#d(d4o0o^x@%s507g+v7xbq6s3$ny=b-kj&&9+5e
    ztc: m4$$4*n@cfp#bc^(g@&*@74@35&4xf&!c-5bsgxf^2q+v7-y*)
  tokenIssuer:
    identifier: token-issuer-seeded
    identifierKey: identifierTokens
    secret: i2r8h1ecJuQ5jLlaKUhzrZwo
    secretKey: secretTokens
    secretName: token-seeder
  tokenSeeder:
    imagePullPolicy: Never
    imageRepo: ghcr.io/vng-realisatie/token-seeder
    pullPolicy: Always
    secret: fW8w1Lzo5WIgdkx6FA47dt4j
    secretKey: internalToken
    tag: 0.1.1
ingress:
  instance: stable
  name: ref-implementatie
  services:
  - host: k8s-zrc-local.test
    name: zrc
    port: 8000
  - host: k8s-drc-local.test
    name: drc
    port: 8000
  - host: k8s-ztc-local.test
    name: ztc
    port: 8000
  - host: k8s-ac-local.test
    name: ac
    port: 8000
  - host: k8s-brc-local.test
    name: brc
    port: 8000
  - host: k8s-nrc-local.test
    name: nrc
    port: 8000
  - host: k8s-tokens-local.test
    name: token-issuer
    port: 8000
  - host: k8s-vrl-local.test
    name: vrl
    port: 8000
postgres:
  images:
    imageRepo: mdillon/postgis
    tag: latest
redis:
  images:
    imageRepo: redis
    tag: 5-alpine
services:
  ac:
    enabled: true
  brc:
    enabled: true
  contactmomenten:
    enabled: true
  drc:
    enabled: true
  klanten:
    enabled: true
  nrc:
    enabled: true
  token-issuer:
    enabled: true
  verzoeken:
    enabled: true
  vrl:
    enabled: true
  zrc:
    enabled: true
  ztc:
    enabled: true
