global:
  celery:
    name: celery
    secretName: celery
  config:
    certManager: true
    createCronJobs: false
    createSecret: true
    enableTLS: false
    environment: minikube
    kube: v1.26.1
    nginx: false
    notificationsDisabled: true
    pullPolicy: Always
  name: ri
  namespace: zgw
  postgres:
    name: postgres
    password: auCz6cVYsxMq7sFPVzmzXRj7
    passwordKey: postgresPassword
    service:
      host: postgres
      port: 5432
    usernameKey: postgresUsername
  rabbitmq:
    defaultUser: nrc_root
    default_password: Rcf4vzrCKOYErl3VDr1h21AM
    name: rabbitmq
    port: 5672
  redis:
    database: 7
    host: redis-test
    name: redis
    service:
      port: 6379
  secretKeys:
    ac: =ljzsa6vv76#-o39sq%zmx8l_lz32)hardh)=a40lrdw6@1sj$
    brc: t%@n#t^%w%s)n53$xz=d@^4+_ftz0m67bv8vqb&$+p%6p8f_!j
    drc: _ev%6ws!@m=h%g+uz9e6*cch1mko4uwhx5$)yq@j&&9r6!$k9=
    nrc: eldhsyl91d8^2w1)d9+v0@^dc2c#ehtg(e1%1g2b$sw-9lp3s8
    zrc: ^ooeqct+60*ndexmivrma1*%zi&l-v+c#0d2voq+))a+s1f$f!
    ztc: '*opg=hly*2#o=k2x9_ii1rpq)0qo$1k%)o5k*37-0#lh=27@s%'
  secrets:
    data:
      brokerUrl: amqp://nrc_root:F9X88AndmgIF6QlhKuUyU6pv@rabbitmq:5672//
      defaultAdminEmail: standaarden.ondersteuning@vng.nl
      defaultAdminPassword: notthepassword
      defaultAdminUser: admin
      postgresPassword: r3TXPOMXI5DQIcfOb94EXdra
      postgresUsername: postgres
      publishBrokerUrl: amqp://nrc_root:F9X88AndmgIF6QlhKuUyU6pv@rabbitmq:5672/%2F
      rabbitmqDefaultDefaultUser: nrc_root
      rabbitmqDefaultPassword: TqzmrbCIzpEJtOtfYHC6XbLI
      resultBackend: amqp://nrc_root:TqzmrbCIzpEJtOtfYHC6XbLI@rabbitmq-nc:5672//
      tokenIssuerIdentifier: token-issuer-seeded
      tokenIssuerSecret: 4lUYRWrfN13GUevfPT0E7AgS
      tokenSeederSecret: qJUj64uleyVASR5fJy9nhTf0
    name: zgw-secrets
  tokenIssuer:
    identifierKey: tokenIssuerIdentifier
    secret: Ue76bqdBzgi0NWXPYCn2Rba7
    secretKey: tokenIssuerSecret
  tokenSeeder:
    imagePullPolicy: Never
    imageRepo: ghcr.io/vng-realisatie/token-seeder
    pullPolicy: Always
    secret: n3jEp4QbVtFItpgcQnMOXJUJ
    secretKey: tokenSeederSecret
    tag: 0.1.1
ingress:
  instance: stable
  name: ref-implementatie
  services:
  - host: k8s-zrc-local.test
    name: zrc
    port: 8000
  - host: k8s-drc-local.test
    name: drc
    port: 8000
  - host: k8s-ztc-local.test
    name: ztc
    port: 8000
  - host: k8s-ac-local.test
    name: ac
    port: 8000
  - host: k8s-brc-local.test
    name: brc
    port: 8000
  - host: k8s-nrc-local.test
    name: nrc
    port: 8000
  - host: k8s-tokens-local.test
    name: token-issuer
    port: 8000
  - host: k8s-vrl-local.test
    name: vrl
    port: 8000
namespace: zgw
postgres:
  images:
    imageRepo: mdillon/postgis
    tag: latest
redis:
  images:
    imageRepo: redis
    tag: 5-alpine
services:
  ac:
    enabled: true
  brc:
    enabled: true
  drc:
    enabled: true
  nrc:
    enabled: true
  token-issuer:
    enabled: true
  vrl:
    enabled: true
  zrc:
    enabled: true
  ztc:
    enabled: true
