global:
  celery:
    name: celery
    secretName: celery
  config:
    certManager: true
    createCronJobs: false
    createJobs: true
    createSecret: false
    enableTLS: true
    environment: test
    kube: 1.23.8
    nginx: false
    pullPolicy: Always
  name: ri
  namespace: zgw-test
  postgres:
    name: postgres
    password: fPJUdnNgSmKwfzE5ah0EexpG
    password_key: password
    secretName: postgres
    service:
      host: postgres
      port: 5432
    username: postgres
    username_key: username
  rabbitmq:
    default_password: ScW77ghcaWDtCHweZ8IzvhRI
    default_user: nrc_root
    name: rabbitmq
    port: 5672
    secretName: rabbitmq
  redis:
    database: 7
    host: redis-test
    name: redis
    service:
      port: 6379
  secret_keys:
    ac: (gd^uf)rp0dd#b96-dv_!$qmu!$c0b(2i1mq%uuwox_r_g*io3
    brc: pcw-5rqt0v#sw_@8m1(!b)mbgz62+&^kgw3%vr5m15g8bo@)h$
    drc: fcdp-o4mmnkcq04^#9^mz(w4yqy9ykvgf7f$c6i3=*k1)mh!7*
    nrc: nry%oi^#wcdjc78y80!kv#f&p=oxy^pdhgn=76+&)qm$1!)a79
    zrc: 9qf@-6@lgm(-g&jyb)h_xqzi-v#)=s&+&xgw6n%bg%bva)%28m
    ztc: jl5zy1e$bg_q_xg7j1nm%20$*6)pj486t_t!#9cus$rn_mm4_n
  tokenIssuer:
    identifier: token-issuer-seeded
    identifierKey: identifierTokens
    secret: XkNH8mAVtFgyd4fHxCBxVCdn
    secretKey: secretTokens
    secretName: token-seeder
  tokenSeeder:
    imagePullPolicy: Never
    imageRepo: ghcr.io/vng-realisatie/token-seeder
    pullPolicy: Always
    secret: 1wmQ6OuZ9PUV3EFLiBN3FuvA
    secretKey: internalToken
    tag: 0.1.1
ingress:
  instance: stable
  name: ref-implementatie
  services:
  - host: zaken-api.test.vng.cloud
    name: zrc
    port: 8000
  - host: documenten-api.test.vng.cloud
    name: drc
    port: 8000
  - host: catalogi-api.test.vng.cloud
    name: ztc
    port: 8000
  - host: autorisaties-api.test.vng.cloud
    name: ac
    port: 8000
  - host: besluiten-api.test.vng.cloud
    name: brc
    port: 8000
  - host: notificaties-api.test.vng.cloud
    name: nrc
    port: 8000
  - host: zaken-auth.test.vng.cloud
    name: token-issuer
    port: 8000
postgres:
  images:
    imageRepo: mdillon/postgis
    tag: latest
redis:
  images:
    imageRepo: redis
    tag: 5-alpine
services:
  ac:
    enabled: true
  brc:
    enabled: true
  contactmomenten:
    enabled: true
  drc:
    enabled: true
  klanten:
    enabled: true
  nrc:
    enabled: true
  token-issuer:
    enabled: true
  verzoeken:
    enabled: true
  vrl:
    enabled: true
  zrc:
    enabled: true
  ztc:
    enabled: true
