global:
  celery:
    name: celery
    secretName: celery
  config:
    certManager: true
    createCronJobs: false
    createSecret: false
    enableTLS: true
    environment: test
    kube: 1.23.8
    nginx: false
    notificationsDisabled: true
    pullPolicy: Always
  name: ri
  namespace: zgw-test
  postgres:
    name: postgres
    password: NHXANoh3urGhNe939URUcRjt
    password_key: password
    secretName: postgres
    service:
      host: postgres
      port: 5432
    username: postgres
    username_key: username
  rabbitmq:
    default_password: l9jhDPEiP0zkmFoXolDDSKrU
    default_user: nrc_root
    name: rabbitmq
    port: 5672
    secretName: rabbitmq
  redis:
    database: 7
    host: redis-test
    name: redis
    service:
      port: 6379
  secret_keys:
    ac: 49epb-72e-mt+965&ecwt0#r*6wii4wx$3vw61!a%)&tozytgb
    brc: t%r1cwfgz3bv12kz)#r3^6t!j24@)-76_f26^fe%oyat&h510m
    drc: =(ms!jq=*5#euwv7xaq99guo))f1gy0dy^88)teug+mt*&=t-6
    nrc: 0m$t8_@%hjs*_oqp*leixhd@#skmru91vdhou#u2_4$=hbz@v6
    zrc: m#duu=ww9%cl-y+(oxa6n9ir0_ve#cqtqbaydendyqp9ez3-5c
    ztc: _83%!2g9si(5sc!z7-9zjlc(6*sh0*+%7y@zu*u-5k9c!x$9zy
  tokenIssuer:
    identifier: token-issuer-seeded
    identifierKey: identifierTokens
    secret: BAgCYETAJghqgtCUdebXOISB
    secretKey: secretTokens
    secretName: token-seeder
  tokenSeeder:
    imagePullPolicy: Never
    imageRepo: ghcr.io/vng-realisatie/token-seeder
    pullPolicy: Always
    secret: AuGOMHMjWoVUfNOvJcx3ETN7
    secretKey: internalToken
    tag: 0.1.1
ingress:
  instance: stable
  name: ref-implementatie
  services:
  - host: zaken-api.test.vng.cloud
    name: zrc
    port: 8000
  - host: documenten-api.test.vng.cloud
    name: drc
    port: 8000
  - host: catalogi-api.test.vng.cloud
    name: ztc
    port: 8000
  - host: autorisaties-api.test.vng.cloud
    name: ac
    port: 8000
  - host: besluiten-api.test.vng.cloud
    name: brc
    port: 8000
  - host: notificaties-api.test.vng.cloud
    name: nrc
    port: 8000
  - host: zaken-auth.test.vng.cloud
    name: token-issuer
    port: 8000
postgres:
  images:
    imageRepo: mdillon/postgis
    tag: latest
redis:
  images:
    imageRepo: redis
    tag: 5-alpine
services:
  ac:
    enabled: true
  brc:
    enabled: true
  contactmomenten:
    enabled: true
  drc:
    enabled: true
  klanten:
    enabled: true
  nrc:
    enabled: true
  token-issuer:
    enabled: true
  verzoeken:
    enabled: true
  vrl:
    enabled: true
  zrc:
    enabled: true
  ztc:
    enabled: true
