global:
  celery:
    name: celery
    secretName: celery
  config:
    certManager: true
    createCronJobs: false
    createJobs: true
    createSecret: true
    enableTLS: false
    environment: pinniped-azure-common-prod
    kube: v1.26.3
    nginx: false
    notificationsDisabled: true
    pullPolicy: Always
  name: ri
  namespace: zgw
  postgres:
    name: postgres
    password: AeaKtiIebmtY5tA56XfbsTjC
    passwordKey: postgresPassword
    service:
      host: postgres
      port: 5432
    usernameKey: postgresUsername
  rabbitmq:
    defaultUser: nrc_root
    default_password: IqoaiZePwOcOcRY0DUDAPlHL
    name: rabbitmq
    port: 5672
  redis:
    database: 7
    host: redis-test
    name: redis
    service:
      port: 6379
  secretKeys:
    ac: 6l6(fqmu1rf6(uwq=y3+kz%gp#zo%4_kvidn^pgs4szc!x$odg
    brc: _pkti%q-i-44*+!4=sa2dv(5)#)v^ss)hlu=f7r_#ph%l6+edf
    drc: 2&6#6c5ccsimg8@adhy-4#gorqns78=ar0@xg7#6s%8k#w(91*
    nrc: jlyb^u1_v12^d#t7o_^n7o0x-7l^2i8c11_2$8dn9vi-!b!8!h
    zrc: a4@#!#q-&62cgie53p$*i6rb$o8%cm+)=_8ks#9==(+8)ja!#)
    ztc: '&zp$!63^tqe&9v5ej!_lundq@r((=zm5v^-zc%7eqxgtr7hs3)'
  secrets:
    data:
      brokerUrl: amqp://nrc_root:4zhXdemdlCxuonJyerfDBjwk@rabbitmq:5672//
      defaultAdminEmail: standaarden.ondersteuning@vng.nl
      defaultAdminPassword: notthepassword
      defaultAdminUser: admin
      postgresPassword: 4AHTFjdovEtLlB9g4TPKnJnX
      postgresUsername: postgres
      publishBrokerUrl: amqp://nrc_root:4zhXdemdlCxuonJyerfDBjwk@rabbitmq:5672/%2F
      rabbitmqDefaultDefaultUser: nrc_root
      rabbitmqDefaultPassword: 4zhXdemdlCxuonJyerfDBjwk
      resultBackend: amqp://nrc_root:4zhXdemdlCxuonJyerfDBjwk@rabbitmq-nc:5672//
      tokenIssuerIdentifier: token-issuer-seeded
      tokenIssuerSecret: afD7pmu4xg0HM44fAunXIprv
      tokenSeederSecret: FN950JhTx44UuSh79PeFitFz
    name: zgw-secrets
  tokenIssuer:
    identifierKey: tokenIssuerIdentifier
    secret: 2Fzbwl1KnTVgXBRm3NdDRmaf
    secretKey: tokenIssuerSecret
  tokenSeeder:
    imagePullPolicy: Never
    imageRepo: ghcr.io/vng-realisatie/token-seeder
    pullPolicy: Always
    secret: 3uTXWfVH5PqfCa407qEmZMiR
    secretKey: tokenSeederSecret
    tag: 0.1.1
ingress:
  instance: stable
  name: ref-implementatie
  services:
  - host: k8s-zrc-local.test
    name: zrc
    port: 8000
  - host: k8s-drc-local.test
    name: drc
    port: 8000
  - host: k8s-ztc-local.test
    name: ztc
    port: 8000
  - host: k8s-ac-local.test
    name: ac
    port: 8000
  - host: k8s-brc-local.test
    name: brc
    port: 8000
  - host: k8s-nrc-local.test
    name: nrc
    port: 8000
  - host: k8s-tokens-local.test
    name: token-issuer
    port: 8000
  - host: k8s-vrl-local.test
    name: vrl
    port: 8000
namespace: zgw
postgres:
  images:
    imageRepo: mdillon/postgis
    tag: latest
redis:
  images:
    imageRepo: redis
    tag: 5-alpine
services:
  ac:
    enabled: true
  brc:
    enabled: true
  drc:
    enabled: true
  nrc:
    enabled: true
  token-issuer:
    enabled: true
  vrl:
    enabled: true
  zrc:
    enabled: true
  ztc:
    enabled: true
