global:
  celery:
    name: celery
    secretName: celery
  config:
    certManager: false
    createCronJobs: true
    createJobs: true
    createSecret: false
    enableTLS: true
    environment: test
    kube: 1.23.8
    nginx: false
    pullPolicy: Always
  name: ri
  namespace: zgw-test
  postgres:
    name: postgres
    password: PzuNFk93DNUnJrhHMBncC0hO
    password_key: password
    secretName: postgres
    service:
      host: postgres
      port: 5432
    username: postgres
    username_key: username
  rabbitmq:
    default_password: 3FR0haXkVhLK6sShrjncotsG
    default_user: nrc_root
    name: rabbitmq
    port: 5672
    secretName: rabbitmq
  redis:
    database: 7
    host: redis-test
    name: redis
    service:
      port: 6379
  secret_keys:
    ac: r^ub8okbx3xp4&whkw+fb40&2d-6zhfjw_y+$bp6omy1cs%kd)
    brc: '@zliaem%!vv3hwdu)rwym6snuo^^z31um+97tx+!wn(0n9maqw'
    drc: '!q!n^@x*z+!e)+nl*mc%7$lewer9k3nz^c&%#i=s_kr^uurwb$'
    nrc: rfkju(5czf-(cq4i7^^h$x+vjs6)c!l^+7i2e%7%3jc(^zflse
    zrc: ozvbgfy1ga(2+p+3y6iaw(do(8mhh)^&9@%p$i-*jr^3n1hkfa
    ztc: zdwb4$#l$#j)!bsjtw_bh)6@huqfzbb57s0690m9^oqypfrqtj
  tokenIssuer:
    identifier: token-issuer-seeded
    identifierKey: identifierTokens
    secret: iohpfrf17dlZw6NgrQMYAZfN
    secretKey: secretTokens
    secretName: token-seeder
  tokenSeeder:
    imagePullPolicy: Never
    imageRepo: ghcr.io/vng-realisatie/token-seeder
    pullPolicy: Always
    secret: 8E3ErKf2IW1aODaai6sPluLz
    secretKey: internalToken
    tag: 0.1.0
ingress:
  instance: stable
  name: ref-implementatie
  services:
  - host: zaken-api.test.vng.cloud
    name: zrc
    port: 8000
  - host: documenten-api.test.vng.cloud
    name: drc
    port: 8000
  - host: catalogi-api.test.vng.cloud
    name: ztc
    port: 8000
  - host: autorisaties-api.test.vng.cloud
    name: ac
    port: 8000
  - host: besluiten-api.test.vng.cloud
    name: brc
    port: 8000
  - host: notificaties-api.test.vng.cloud
    name: nrc
    port: 8000
  - host: referentielijsten-api.test.vng.cloud
    name: vrl
    port: 8000
  - host: zaken-auth.test.vng.cloud
    name: token-issuer
    port: 8000
postgres:
  images:
    imageRepo: mdillon/postgis
    tag: latest
redis:
  images:
    imageRepo: redis
    tag: 5-alpine
services:
  ac:
    enabled: true
  brc:
    enabled: true
  contactmomenten:
    enabled: true
  drc:
    enabled: true
  klanten:
    enabled: true
  nrc:
    enabled: true
  token-issuer:
    enabled: true
  verzoeken:
    enabled: true
  vrl:
    enabled: true
  zrc:
    enabled: true
  ztc:
    enabled: true
