global:
  celery:
    name: celery
    secretName: celery
  config:
    certManager: true
    createCronJobs: false
    createJobs: true
    createSecret: true
    enableTLS: false
    environment: minikube
    kube: v1.26.1
    nginx: false
    notificationsDisabled: true
    pullPolicy: Always
  name: ri
  namespace: zgw
  postgres:
    name: postgres
    password: J15h6guzfTsFIhzvIrgl5Vev
    passwordKey: postgresPassword
    service:
      host: postgres
      port: 5432
    usernameKey: postgresUsername
  rabbitmq:
    defaultUser: nrc_root
    default_password: 6mtj75qI12rQpoxJJegGfPAI
    name: rabbitmq
    port: 5672
  redis:
    database: 7
    host: redis-test
    name: redis
    service:
      port: 6379
  secretKeys:
    ac: qnppxegd=6jlr-n96!l5c2i9owil#95q9@3uyc^8@#wkjpybn^
    brc: y^kb$#@ij!ndhl(9h-38!^ipt5spwict6o(sd)7zyuxlqx%s@x
    drc: 8+y$poy&scsj9_j*rp@l69@=w=^!v$h)=y-1iy_n78i1wo0vk!
    nrc: +$n=!nx^ssddef41gluccyo!u(!mx9uux4*e8^$)ql$^^9$!(_
    zrc: tfm@p$de2!kd88ygh(8o2%3tsawdlsg&4(dk3wyeh42oltg&#r
    ztc: '!b*4g7j@b)*@qs$rds9%&ske#w@rd-2rlx!0!a7d3gm@a=-o%!'
  secrets:
    data:
      brokerUrl: amqp://nrc_root:F9X88AndmgIF6QlhKuUyU6pv@rabbitmq:5672//
      defaultAdminEmail: admin@test.nl
      defaultAdminPassword: notthepassword
      defaultAdminUser: admin
      postgresPassword: r3TXPOMXI5DQIcfOb94EXdra
      psotgresUsername: postgres
      publishBrokerUrl: amqp://nrc_root:F9X88AndmgIF6QlhKuUyU6pv@rabbitmq:5672/%2F
      rabbitmqDefaultDefaultUser: nrc_root
      rabbitmqDefaultPassword: F9X88AndmgIF6QlhKuUyU6pv
      resultBackend: amqp://nrc_root:F9X88AndmgIF6QlhKuUyU6pv@rabbitmq-nc:5672//
      tokenIssuerIdentifier: token-issuer-seeded
      tokenIssuerSecret: cLjYcy44IB3wlXNf0XE2T7o8
      tokenSeederSecret: QsJC17crCKio4iSCvZntmHSN
    name: zgw-secrets
  tokenIssuer:
    identifierKey: tokenIssuerIdentifier
    secret: swBccNjw22sFvhHA0D7D5xQB
    secretKey: tokenIssuerSecret
  tokenSeeder:
    imagePullPolicy: Never
    imageRepo: ghcr.io/vng-realisatie/token-seeder
    pullPolicy: Always
    secret: HENp8b4FvIsU6QJfulUS4Jdj
    secretKey: tokenSeederSecret
    tag: 0.1.1
ingress:
  instance: stable
  name: ref-implementatie
  services:
  - host: k8s-zrc-local.test
    name: zrc
    port: 8000
  - host: k8s-drc-local.test
    name: drc
    port: 8000
  - host: k8s-ztc-local.test
    name: ztc
    port: 8000
  - host: k8s-ac-local.test
    name: ac
    port: 8000
  - host: k8s-brc-local.test
    name: brc
    port: 8000
  - host: k8s-nrc-local.test
    name: nrc
    port: 8000
  - host: k8s-tokens-local.test
    name: token-issuer
    port: 8000
  - host: k8s-vrl-local.test
    name: vrl
    port: 8000
namespace: zgw
postgres:
  images:
    imageRepo: mdillon/postgis
    tag: latest
redis:
  images:
    imageRepo: redis
    tag: 5-alpine
services:
  ac:
    enabled: true
  brc:
    enabled: true
  drc:
    enabled: true
  nrc:
    enabled: true
  token-issuer:
    enabled: true
  vrl:
    enabled: true
  zrc:
    enabled: true
  ztc:
    enabled: true
