global:
  celery:
    name: celery
    secretName: celery
  config:
    certManager: true
    createCronJobs: false
    createJobs: false
    createSecret: false
    enableTLS: true
    environment: local
    kube: 1.23.8
    nginx: false
    pullPolicy: Always
  name: ri
  namespace: zgw
  postgres:
    name: postgres
    password: Yw9hkQ5aRO6MoYwYjf7Z9he8
    password_key: password
    secretName: postgres
    service:
      host: postgres
      port: 5432
    username: postgres
    username_key: username
  rabbitmq:
    default_password: azyG1OxqABz502qaZQQikoVi
    default_user: nrc_root
    name: rabbitmq
    port: 5672
    secretName: rabbitmq
  redis:
    database: 7
    host: redis-test
    name: redis
    service:
      port: 6379
  secret_keys:
    ac: p3-8*#$(!0_l(zw_&*3v0*(wbq^vt1)94(@j)dy2(4i#d0_@ba
    brc: $86kpzn!5+0ur09o=#22^0xg(zam1bg0kb3%npoao9hgppo3l4
    drc: e9qmzi)8&f!1l#o^@x^b^tkq#igipwjrsxn8&uc1=__k(zp-=y
    nrc: sbp8fi%s=yhsuqp5@das0%ua)pz#o&)!gvj1=qbml#4i8oy_r0
    zrc: )e(5^k#keqimw-6-t2zfx01ypjn*5(^n=!fo2uamx5#$nfk!5+
    ztc: z8*(#*5#=7bqu4a3fk!ah@l*$-eq0&172m#x!&7#4ytus(@&=o
  tokenIssuer:
    identifier: token-issuer-seeded
    identifierKey: identifierTokens
    secret: BK7KzfT4bJDgJ5Ydr3K4I91O
    secretKey: secretTokens
    secretName: token-seeder
  tokenSeeder:
    imagePullPolicy: Never
    imageRepo: ghcr.io/vng-realisatie/token-seeder
    pullPolicy: Always
    secret: YGEYu6IHRgDkjFOTZd1gjuKF
    secretKey: internalToken
    tag: 0.1.1
ingress:
  instance: stable
  name: ref-implementatie
  services:
  - host: zaken-api.vng.cloud
    name: zrc
    port: 8000
  - host: documenten-api.vng.cloud
    name: drc
    port: 8000
  - host: catalogi-api.vng.cloud
    name: ztc
    port: 8000
  - host: autorisaties-api.vng.cloud
    name: ac
    port: 8000
  - host: besluiten-api.vng.cloud
    name: brc
    port: 8000
  - host: notificaties-api.vng.cloud
    name: nrc
    port: 8000
  - host: zaken-auth.vng.cloud
    name: token-issuer
    port: 8000
  - host: referentielijsten-api.vng.cloud
    name: vrl
    port: 8000
postgres:
  images:
    imageRepo: mdillon/postgis
    tag: latest
redis:
  images:
    imageRepo: redis
    tag: 5-alpine
services:
  ac:
    enabled: true
  brc:
    enabled: true
  contactmomenten:
    enabled: true
  drc:
    enabled: true
  klanten:
    enabled: true
  nrc:
    enabled: true
  token-issuer:
    enabled: true
  verzoeken:
    enabled: true
  vrl:
    enabled: true
  zrc:
    enabled: true
  ztc:
    enabled: true
