config:
  host: k8s-vrl-local.test,localhost,zaken-api.vng.cloud,vrl
  ingressHost: k8s-vrl-local.test
cronjob:
  expression: 15 3 1 * *
  run: true
database:
  name: vrl
job:
  run: true
replicas:
  max: 2
  min: 1
secret:
  key: SECRET_KEY
  name: vrl-secret
  sentry: SENTRY_DSN
service:
  images:
    imageRepo: vngr/vng-referentielijsten
    tag: 0.5.6
  name: vrl
  port: 8000
