config:
  env: local
  host: k8s-ztc-local.test,localhost,ztc,ztc.zgw.svc.cluster.local
  pullPolicy: Never
cronjob:
  expression: 15 3 1 * *
database:
  name: ztc
replicas:
  max: 2
  min: 1
secret:
  key: SECRET_KEY
  name: ztc-secret
  sentry: SENTRY_DSN
service:
  images:
    imageRepo: ztc
    tag: test4
  name: ztc
  port: 8000
