config:
  host: k8s-zrc-local.test,localhost,zrc
cronjob:
  expression: 15 3 1 * *
database:
  name: zrc
replicas:
  max: 2
  min: 1
secret:
  key: SECRET_KEY
  name: zrc-secret
  sentry: SENTRY_DSN
service:
  images:
    imageRepo: vngr/gemma-zrc
    tag: 1.3.0
  name: zrc
  port: 8000
