config:
  host: k8s-vrl-local.test,localhost,zaken-api.vng.cloud
  ingressHost: k8s-vrl-local.test

database:
  name: vrl

job:
  run: true

replicas:
  min: 1
  max: 2

cronjob:
  run: true
  # At 03:15 on day-of-month 1
  expression: "15 3 1 * *"

service:
  name: vrl
  port: 8000
  images:
    imageRepo: vngr/vng-referentielijsten
    tag: 0.5.6

secret:
  name: vrl-secret
  sentry: SENTRY_DSN
  key: SECRET_KEY
