apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.api_secrets.brc.name }}
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  {{ .Values.api_secrets.key }}: {{ .Values.secret_keys.brc | b64enc }}
