apiVersion: v1
kind: Secret
metadata:
  name:  {{ .Values.celery.secretName }}
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  publish_broker_url: "amqp://{{ .Values.rabbitmq.default_user }}:{{ .Values.rabbitmq.default_password }}@{{ .Values.rabbitmq.name}}:{{ .Values.rabbitmq.port}}/%2F"
  broker_url: "amqp://{{ .Values.rabbitmq.default_user }}:{{ .Values.rabbitmq.default_password }}@{{ .Values.rabbitmq.name}}:{{ .Values.rabbitmq.port}}//"
  result_backend: "amqp://{{ .Values.rabbitmq.default_user }}:{{ .Values.rabbitmq.default_password }}@{{ .Values.rabbitmq.name}}-nc:{{ .Values.rabbitmq.port}}//"
