apiVersion: v1
kind: Secret
metadata:
  name:  {{ .Values.postgres.secretName }}
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  {{ .Values.postgres.username_key }}: {{ .Values.postgres.username | b64enc }}
  {{ .Values.postgres.password_key }}: {{ .Values.postgres.password | b64enc }}

