apiVersion: v1
kind: Secret
metadata:
  name:  {{ .Values.rabbitmq.secretName }}
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  default_user: {{ .Values.rabbitmq.default_user | b64enc }}
  default_password: {{ .Values.rabbitmq.default_password | b64enc }}
