config:
  baseAddress: http://zrc.zgw.svc.cluster.local
  env: local
  githubApiSpec: https://raw.githubusercontent.com/VNG-Realisatie/gemma-zaken/master/api-specificatie/zrc/current_version/openapi.yaml
  host: k8s-zrc-local.test,localhost,zrc,zrc.zgw.svc.cluster.local
  pullPolicy: Always
cronjob:
  expression: 15 3 1 * *
database:
  name: zrc
replicas:
  max: 2
  min: 1
secret:
  key: SECRET_KEY
  name: zrc-secret
service:
  images:
    imageRepo: ghcr.io/vng-realisatie/zaken-api
    tag: 1.5.0
  name: zrc
  port: 8000
