---

db_host: postgis
redis_cache: redis


scaler:
  min: 1
  max: 3

services:
  # Datastores

  - name: postgis
    templates: ../k8s/database/
    pvc_name: db
    sub_path: database
    databases:
      - zrc
      - drc
      - ztc
      - brc
      - nrc
      - ac
      - token-issuer
      - deploy
      - klanten
      - contactmomenten
      - verzoeken

  - name: redis
    templates: ../k8s/cache/

  # Official APIs

  - name: ac
    templates: ../k8s/ac/
    domain: autorisaties-api.vng.cloud
    image_tag: '1.0.0'

  - name: brc
    templates: ../k8s/brc/
    domain: besluiten-api.vng.cloud
    image_tag: '1.0.1.post0'

  - name: drc
    templates: ../k8s/drc/
    domain: documenten-api.vng.cloud
    image_tag: '1.3.0'
    min_upload_size: 4294967296  # 4GB

  - name: nrc
    templates: ../k8s/nrc/
    domain: notificaties-api.vng.cloud
    image_tag: '1.0.0.post1'

  - name: zrc
    templates: ../k8s/zrc/
    domain: zaken-api.vng.cloud
    image_tag: '1.4.0'

  - name: ztc
    templates: ../k8s/ztc/
    domain: catalogi-api.vng.cloud
    image_tag: '1.2.1'

  - name: klanten
    templates: ../k8s/klanten/
    domain: klanten-api.vng.cloud
    image_tag: 'latest'

  - name: contactmomenten
    templates: ../k8s/contactmomenten/
    domain: contactmomenten-api.vng.cloud
    image_tag: 'latest'

  - name: verzoeken
    templates: ../k8s/verzoeken/
    domain: verzoeken-api.vng.cloud
    image_tag: 'latest'

  # Unofficial APIs
  - name: vrl
    templates: ../k8s/vrl/
    domain: referentielijsten-api.vng.cloud
    image_tag: '0.1.1'

  # Supporting services

  - name: token-issuer
    templates: ../k8s/tokens
    image_tag: '0.6.2'
    redis_host: redis-test
    redis_db: 7
    host: zaken-auth.vng.cloud

  # - name: inway
  #   templates: ../k8s/inway/

ingress:
  name: ref-implementatie
  instance: zgw-stable
  services:
    # Official APIs

    - host: zaken-api.vng.cloud
      name: zrc
    - host: documenten-api.vng.cloud
      name: drc
    - host: catalogi-api.vng.cloud
      name: ztc
    - host: autorisaties-api.vng.cloud
      name: ac
    - host: besluiten-api.vng.cloud
      name: brc
    - host: notificaties-api.vng.cloud
      name: nrc
    - host: klanten-api.vng.cloud
      name: klanten
    - host: contactmomenten-api.vng.cloud
      name: contactmomenten
    - host: verzoeken-api.vng.cloud
      name: verzoeken

    # Unofficial APIs

    - host: referentielijsten-api.vng.cloud
      name: vrl

    # Supporting services

    - host: zaken-auth.vng.cloud
      name: token-issuer
