config:
  env: kubernetes
  host: zaken-auth.test.vng.cloud,localhost,token-issuer,token-issuer.zgw-test.svc.cluster.local
  pullPolicy: Always
replicas:
  max: 2
  min: 1
secret:
  name: tokens-secret
service:
  images:
    imageRepo: ghcr.io/vng-realisatie/token-issuer
    tag: 0.0.2
  name: token-issuer
  port: 8000
