config:
  env: kubernetes
  host: k8s-tokens-local.test,localhost,token-issuer,token-issuer.zgw.svc.cluster.local
  pullPolicy: Always
replicas:
  max: 2
  min: 1
secret:
  name: tokens-secret
service:
  images:
    imageRepo: ghcr.io/vng-realisatie/token-issuer
    tag: 0.1.0
  name: token-issuer
  port: 8000
