config:
  baseAddress: https://notificaties-api.test.vng.cloud
  env: test
  host: notificaties-api.test.vng.cloud,localhost,nrc,nrc.zgw-test.svc.cluster.local
  pullPolicy: Always
cronjob:
  expression: 15 3 1 * *
database:
  name: nrc
replicas:
  max: 2
  min: 1
secret:
  key: SECRET_KEY
  name: nrc-secret
service:
  images:
    imageRepo: ghcr.io/vng-realisatie/notificaties-api
    tag: 1.0.0.post1
  name: nrc
  port: 8000
