config:
  baseAddress: http://brc.zgw.svc.cluster.local
  env: local
  host: k8s-brc-local.test,localhost,brc,brc.zgw.svc.cluster.local
  pullPolicy: Always
cronjob:
  expression: 15 3 1 * *
database:
  name: brc
replicas:
  max: 2
  min: 1
secret:
  key: SECRET_KEY
  name: brc-secret
service:
  images:
    imageRepo: ghcr.io/vng-realisatie/besluiten-api
    tag: 1.0.1.post0
  name: brc
  port: 8000
