kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ .Values.service.name }}-private-media
  namespace: {{ .Values.global.namespace}}
spec:
  storageClassName: {{ template "zgw.storageClassName" . }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
