config:
  host: k8s-nrc-local.test,localhost,nrc
cronjob:
  expression: 15 3 1 * *
database:
  name: nrc
replicas:
  max: 2
  min: 1
secret:
  key: SECRET_KEY
  name: nrc-secret
  sentry: SENTRY_DSN
service:
  images:
    imageRepo: vngr/notificaties-api
    tag: 1.0.0.post1
  name: nrc
  port: 8000
