config:
  host: k8s-brc-local.test,localhost,besluiten-api.vng.cloud
  ingressHost: k8s-brc-local.test

database:
  name: brc

job:
  run: true

replicas:
  min: 1
  max: 2

cronjob:
  run: true
  # At 03:15 on day-of-month 1
  expression: "15 3 1 * *"

service:
  name: brc
  port: 8000
  images:
    imageRepo: vngr/gemma-brc
    tag: latest

secret:
  name: brc-secret
  sentry: SENTRY_DSN
  key: SECRET_KEY
