config:
  host: k8s-zrc-local.test,localhost,zaken-api.vng.cloud,zrc
  ingressHost: k8s-zrc-local.test
cronjob:
  expression: 15 3 1 * *
  run: true
database:
  name: zrc
job:
  run: true
replicas:
  max: 2
  min: 1
secret:
  key: SECRET_KEY
  name: zrc-secret
  sentry: SENTRY_DSN
service:
  images:
    imageRepo: vngr/gemma-zrc
    tag: 1.3.0
  name: zrc
  port: 8000
