kind: Deployment
apiVersion: apps/v1
metadata:
  name: {{ .Values.global.rabbitmq.name }}
  namespace: {{ .Values.global.namespace}}
  labels:
    {{- include "ri.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Values.global.rabbitmq.name }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Values.global.rabbitmq.name }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
      - name: rabbitmq
        image: rabbitmq:3.7-alpine
        env:
          - name: RABBITMQ_DEFAULT_USER
            valueFrom:
              secretKeyRef:
                name: {{ .Values.global.secrets.name }}
                key: rabbitmqDefaultDefaultUser
          - name: RABBITMQ_DEFAULT_PASS
            valueFrom:
              secretKeyRef:
                name: {{ .Values.global.secrets.name }}
                key: rabbitmqDefaultPassword
