{{ if .Values.global.config.createSecret }}
apiVersion: v1
kind: Secret
metadata:
  name:  {{ .Values.global.celery.secretName }}
  namespace: {{ .Values.global.namespace }}
type: Opaque
stringData:
  publish_broker_url: "amqp://{{ .Values.global.rabbitmq.default_user }}:{{ .Values.global.rabbitmq.default_password }}@{{ .Values.global.rabbitmq.name}}:{{ .Values.global.rabbitmq.port}}/%2F"
  broker_url: "amqp://{{ .Values.global.rabbitmq.default_user }}:{{ .Values.global.rabbitmq.default_password }}@{{ .Values.global.rabbitmq.name}}:{{ .Values.global.rabbitmq.port}}//"
  result_backend: "amqp://{{ .Values.global.rabbitmq.default_user }}:{{ .Values.global.rabbitmq.default_password }}@{{ .Values.global.rabbitmq.name}}-nc:{{ .Values.global.rabbitmq.port}}//"
{{end}}