config:
  host: k8s-verzoeken-local.test,localhost,verzoeken-api.vng.cloud,verzoeken
  ingressHost: k8s-verzoeken-local.test
cronjob:
  expression: 15 3 1 * *
  run: true
database:
  name: verzoeken
job:
  run: true
replicas:
  max: 2
  min: 1
secret:
  key: SECRET_KEY
  name: verzoeken-secret
  sentry: SENTRY_DSN
service:
  images:
    imageRepo: vngr/verzoeken-api
    tag: 0.1.0
  name: verzoeken
  port: 8000
