config:
  host: k8s-ztc-local.test,localhost,catalogi-api.vng.cloud
  ingressHost: k8s-ztc-local.test

database:
  name: ztc

job:
  run: true

replicas:
  min: 1
  max: 2

cronjob:
  run: true
  # At 03:15 on day-of-month 1
  expression: "15 3 1 * *"

service:
  name: ztc
  port: 8000
  images:
    imageRepo: vngr/gemma-ztc
    tag: 1.1.0.post0

secret:
  name: ztc-secret
  sentry: SENTRY_DSN
  key: SECRET_KEY
