---

# Deployment

kind: Deployment
apiVersion: apps/v1
metadata:
  name: {{ service.name }}
  namespace: zgw
  labels:
    k8s-app: {{ service.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: {{ service.name }}
  template:
    metadata:
      name: {{ service.name }}
      labels:
        k8s-app: {{ service.name }}
    spec:
      containers:
      - name: {{ service.name }}
        image: ghcr.io/vng-realisatie/referentielijsten-api:{{ service.image_tag }}
        imagePullPolicy: Always
        resources:
          requests:
            memory: "50Mi"
            cpu: "50m"
          limits:
            memory: "100Mi"
            cpu: "100m"
        readinessProbe:
          httpGet:
            path: /api/v1/health
            port: 8000
            httpHeaders:
              - name: Host
                value: localhost
          initialDelaySeconds: 10
          periodSeconds: 30
        livenessProbe:
          httpGet:
            path: /api/v1/health
            port: 8000
            httpHeaders:
              - name: Host
                value: localhost
          initialDelaySeconds: 10
          periodSeconds: 30

        env:
          - name: PORT
            value: :8000

---

# Service

kind: Service
apiVersion: v1
metadata:
  name: {{ service.name }}
  namespace: zgw
  labels:
    k8s-app: {{ service.name }}
spec:
  selector:
    k8s-app: {{ service.name }}
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000
