config:
  host: k8s-contactmomenten-local.test,localhost,contactmomenten-api.test.vng.cloud
  ingressHost: k8s-contactmomenten-local.test

database:
  name: contactmomenten

job:
  run: true

replicas:
  min: 1
  max: 2

cronjob:
  run: true
  # At 03:15 on day-of-month 1
  expression: "15 3 1 * *"

service:
  name: contactmomenten
  port: 8000
  images:
    imageRepo: vngr/contactmomenten-api
    tag: latest

secret:
  name: contactmomenten-secret
  sentry: SENTRY_DSN
  key: SECRET_KEY
