config:
  host: k8s-contactmomenten-local.test,localhost,contactmomenten
cronjob:
  expression: 15 3 1 * *
database:
  name: contactmomenten
replicas:
  max: 2
  min: 1
secret:
  key: SECRET_KEY
  name: contactmomenten-secret
  sentry: SENTRY_DSN
service:
  images:
    imageRepo: vngr/contactmomenten-api
    tag: 1.1.0
  name: contactmomenten
  port: 8000
