config:
  host: referentielijsten-api.test.vng.cloud,localhost,vrl,vrl.zgw-test.svc.cluster.local
  ingressHost: k8s-vrl-local.test
  pullPolicy: Always
cronjob:
  expression: 15 3 1 * *
database:
  name: vrl
replicas:
  max: 2
  min: 1
secret:
  key: SECRET_KEY
  name: vrl-secret
service:
  images:
    imageRepo: ghcr.io/vng-realisatie/referentielijsten-api
    tag: 0.1.3
  name: vrl
  port: 8000
