config:
  branch: ''
  host: k8s-ac-local.test,localhost,ac
cronjob:
  expression: 15 3 1 * *
database:
  name: ac
replicas:
  max: 2
  min: 1
secret:
  key: SECRET_KEY
  name: ac-secret
  sentry: SENTRY_DSN
service:
  images:
    imageRepo: vngr/autorisaties-api
    tag: 1.0.0
  name: ac
  port: 8000
