config:
  host: k8s-drc-local.test,localhost,drc
cronjob:
  expression: 15 3 1 * *
database:
  name: drc
replicas:
  max: 2
  min: 1
secret:
  key: SECRET_KEY
  name: drc-secret
  sentry: SENTRY_DSN
service:
  images:
    imageRepo: vngr/gemma-drc
    tag: 1.2.0
  minUploadSize: '4294967296'
  name: drc
  port: 8000
