{{ if .Values.job.run }}
apiVersion: batch/v1
kind: Job
metadata:
  name:  {{ .Values.service.name }}-seeder
  namespace: {{ .Values.global.namespace}}
spec:
  ttlSecondsAfterFinished: 120
  template:
    spec:
      initContainers:
      - name: wait-for-postgres
        image: busybox:1.31
        command: [ 'sh', '-c', 'echo -e "Checking for the availability of postgres deployment"; while ! nc -z postgres 5432; do sleep 1; printf "-"; done; echo -e "  >> POSTGRES has started";' ]
      containers:
      - name: seeder
        image: bitnami/postgresql:latest
        command: ["createdb"]
        args: ["-h", "{{.Values.global.postgres.service.host }}", "-p", "{{.Values.global.postgres.service.port}}", "-U", "$(POSTGRES_USER)", {{ .Values.database.name }} ]
        env:
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                name: {{ .Values.global.postgres.secretName }}
                key: {{ .Values.global.postgres.username_key }}
          - name: PGPASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ .Values.global.postgres.secretName }}
                key: {{ .Values.global.postgres.password_key }}
      restartPolicy: Never
  {{end}}
