apiVersion: apps/v1
kind: Deployment
metadata:
  name:  {{ .Values.service.name }}
  namespace: {{ .Values.global.namespace}}
  labels:
    {{- include "ri.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Values.service.name }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Values.service.name }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Values.service.name }}
          image: {{ .Values.service.images.imageRepo}}:{{ .Values.service.images.tag }}
          ports:
            - containerPort: {{ .Values.service.port }}
          env:
            - name: TOKEN_ISSUER_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.global.tokenIssuer.secretName }}
                  key: {{ .Values.global.tokenIssuer.secretKey }}
            - name: TOKEN_ISSUER_IDENTIFIER
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.global.tokenIssuer.secretName }}
                  key: {{ .Values.global.tokenIssuer.identifierKey }}
            - name: ENV
              value: {{ .Values.config.env }}
            - name: PORT
              value: {{ .Values.service.port | squote }}
            - name: PYTHONUNBUFFERED
              value: "1"
          command: ["python3", "main.py"]
          resources:
            requests:
              memory: "100Mi"
              cpu: "50m"
            limits:
              memory: "200Mi"
              cpu: "100m"
