name: ci

on:
  push:
    branches:
      - 'main'
      - 'feature/add-cicd'
    tags:
      - "v*.*.*"

env:
  CHART_NAME: ri-zgw
  IMAGE_TAG: 0.0.1
  ENV: production

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: helm login
        run: |
          echo ${{ secrets.GHCR_TOKEN }} | helm registry login ghcr.io -u $ --password-stdin
      - name: helm package
        run: |
          helm package ./helm/ri --version $IMAGE_TAG
      - name: helm push
        if: ${{ github.event_name == 'push' }}
        run: |
          REPO_NAME=$(echo 'print("abc".upper())' | python3 -)
          helm push $CHART_NAME-$IMAGE_TAG.tgz oci://ghcr.io/$REPO_NAME