name: test

on:
  pull_request:
    branches:
      - "main"

env:
  ENV: test

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 'pypy3.9'
      - run: |
          cd ./parser
          pip install -r requirements.txt
          python3 parser.py
      - name: helm login
        run: |
          echo ${{ secrets.GHCR_TOKEN }} | helm registry login ghcr.io -u $ --password-stdin
      - name: helm lint
        run: |
          helm lint ./helm/ri-zgw
      - name: helm package
        run: |
          helm package ./helm/ri-zgw
      - name: helm push
        run: |
          REPO_NAME=$(echo 'print("${{ github.repository_owner }}".lower())' | python3 -)
          CHART=$(ls | grep ri-zgw-*.tgz)
          helm push $CHART oci://ghcr.io/$REPO_NAME
