apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.name }}
  namespace: {{ .Values.global.namespace }}
type: Opaque
data:
  {{ .Values.secret.key }}: {{ .Values.global.secret_keys.zrc | b64enc }}
  {{ .Values.secret.sentry }}: {{ .Values.global.sentry_dsn.zrc | b64enc }}
